apiVersion: v1
kind: Service
metadata:
  name: python-fastapi-project-skeleton
spec:
  selector:
    app: python-fastapi-project-skeleton
  ports:
    - name: http
      port: 80
      targetPort: 8000
  type: ClusterIP
